config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  resources :categories do
    resources :tasks
  end

  #ito dinagdag ko
  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/categories/', to: 'categories#index'
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  attribute :completed, :boolean, default: false

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

  # protected

  def after_sign_in_path_for(resource)
    authenticated_root_path # Or any other path
  end
end

#ang original ay walang laman ang class method

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #kakalagay ko to
  before_action :authenticate_user!


  # def index
  #   @categories = Category.all
  # end

  def index
    @categories = current_user.categories
    @todays_tasks = Task.where(schedule_date: Date.today)
  end



  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end


  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      # Redirect to the categories index with a success message
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      # Render the 'new' form again so the user can fix problems
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = @category.tasks.build
  end

  def show

  end

  def create
    @task = @category.tasks.build(task_params)
    if @task.save
      redirect_to @category, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to @category, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to @category, notice: 'Task was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  end

  # def task_params
  #   params.require(:task).permit(:title, :description, :category_id)
  # end

  def task_params
    params.require(:task).permit(:title, :description, :schedule_date, :completed, :category_id)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <%= form_with(model: category, local: true) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, class: "control-label" %>
      <%= form.text_field :name, class: "form-control", id: :category_name %>
    </div>

    <div class="form-group">
      <%= form.label :description, class: "control-label" %>
      <%= form.text_area :description, class: "form-control", id: :category_description %>
    </div>

    <div class="form-group">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<!-- For edit -->
<h1>Edit Category</h1>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>



<div class="container mt-5">
  <h1 class="mb-4">Property Maintenance Job Requests</h1>
  <%= link_to 'New Apartment + ', new_category_path, class: 'btn btn-primary mb-4' %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Apartment</th>
        <th scope="col">Description</th>
        <th scope="col">Maintenance Job Request</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.description %></td>
          <td><%= link_to 'Show', category, class: 'btn btn-success mr-1' %>
 </td>
          <td class="btn-group" role="group" aria-label="Basic mixed styles example">
         
            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning mr-1' %>
            <%= button_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-1' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<br>

<div class="container mt-3">
  <div class="text-center">
    <h2 class="mb-4">Today's Scheduled Tasks</h2>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Category</th>
          <th scope="col">Scheduled Date</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @todays_tasks.each do |task| %>
          <tr>
            <td style="<%= task.completed ? 'text-decoration: line-through;' : '' %>"><%= task.title %></td>
            <td><%= task.category.name %></td>
            <td><%= task.scheduled_date %></td>
            <td>
              <%= link_to 'Edit', edit_category_task_path(task.category, task), class: 'btn btn-warning btn-sm mr-1' %>
              <%= button_to 'Delete', category_task_path(task.category, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>






<%# 'btn btn-success mr-1' - success
'btn btn-danger mr-1' - danger %>

app/views/categories/new.html.erb
<!-- For new -->
<h1>New Category</h1>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Tasks</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @category.tasks.each do |task| %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.description %></td>
              <td>
                <%= link_to 'Show', category_task_path(@category, task), class: 'btn btn-info btn-sm' %>
                <%= link_to 'Edit', edit_category_task_path(@category, task), class: 'btn btn-warning btn-sm' %>
                <%= button_to 'Destroy', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= link_to 'New Task', new_category_task_path(@category), class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="row">
    <div class="col text-center">
      <%= link_to 'Edit Category', edit_category_path(@category), class: 'btn btn-secondary' %> |
      <%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Property Management Maintenance Application</title>
  <style>
    body {
      background-color: #grey;
      display: flex;
      justify-content: center;
      align-items: top;
      height: 100vh;
      margin-top: 200px;
    }
    .container {
      text-align: center;
    }

    h1{
      color: gray;
      font-size: 80px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Property Management Maintenance Application</h1><br><br><br><br>
    <p>Please sign in or register to get started:</p><br>
    <p>
      <%= link_to 'Sign In', new_user_session_path %> |
      <%= link_to 'Register', new_user_registration_path %>
    </p>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <title>PropertyManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_link_tag 'categories', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  </head>



  <body>
 <nav>
    

  
    <%= yield %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: [@category, @task], local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :task_description, class: "form-control" %>
  </div>

  <!-- If you have additional fields specific to tasks, add them here -->



<div class="form-group">
  <%= form.label :schedule_date %>
  <%# ito ang original %>
  <%# <%= form.date_field :schedule_date, id: :task_schedule_date, class: 'form-control' %> 
<%# pinalitan ko nito %>
<%= form.date_field :schedule_date, class: 'form-control' %>

</div>

  <div class="actions">
    <%= form.submit "Save Task", class: "btn btn-primary" %>
  </div>

  

<% end %>

app/views/tasks/edit.html.erb
<!-- For edit -->
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/new.html.erb
<!-- For new -->
<h1>New Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="container">
  <p id="notice" class="text-danger font-size-18"><%= notice %></p>

  <div class="row">
    <div class="col">
      <p>
        <strong>Name:</strong>
        <%= @category.name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @category.description %>
      </p>

      <h2>Tasks</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @category.tasks.each do |task| %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.description %></td>
              <td>
                <%= link_to 'Show', category_task_path(@category, task), class: "btn btn-info btn-sm" %>
                <%= link_to 'Edit', edit_category_task_path(@category, task), class: "btn btn-warning btn-sm" %>
                <%= button_to 'Destroy', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New Task', new_category_task_path(@category), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col text-center">
      <%= link_to 'Edit Category', edit_category_path(@category), class: "btn btn-secondary" %> |
      <%= link_to 'Back to Categories', categories_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>